# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 1
  - name: Publications
    url: /#publications
    weight: 2
#  - name: Talks
#    url: /#talks
#    weight: 3
  - name: News
    url: /news
    weight: 4
  - name: Experience
    url: experience/
    weight: 5
#  - name: Projects
#    url: projects/
#    weight: 6
  - name: Fieldwork
    url: fieldwork/
    weight: 7
#  - name: Teaching
#    url: teaching/
#    weight: 8
